### ISSUE TITLE
Can this library serialize a field of type `Vec` to Prometheus' histogram?

### ISSUE THREAD

**Issue by changweige** [w4/serde_prometheus#1]

**Comment by w4** [comment]
Hi,

There's no direct support for generating a histogram, but it can easily implemented in your application or a higher level library. There is some support for serialising a histogram using `serde_prometheus` in `metered-rs`, however it's worth noting this generates a _summary_ not a histogram. But it serves as a fairly decent base for histograms: https://github.com/magnet/metered-rs/commit/b6b61979a2727e3be58737015ba11eb63309ed6b

**Comment by changweige** [comment]
Thanks. It really helps
